# Generated by Django 6.1 on 2026-09-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive members keep their history but are skipped in rotations.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
