# Generated by Django 6.1 on 2026-09-02 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_chore'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_slots', to='chores.chore')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotation_slots', to='chores.member')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('chore', 'member'), name='unique_member_per_chore_rotation')],
            },
        ),
    ]
