# Generated by Django 6.1 on 2026-09-02 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_rotationslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done')], default='open', max_length=10)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='chores.chore')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='chores.member')),
            ],
            options={
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='assignment_status_due_idx')],
            },
        ),
    ]
